tasks:
  - before: corepack prepare && corepack enable
    init: |
      echo "ADMIN_ENDPOINT=${ADMIN_ENDPOINT}" > .env
      pnpm install
    command: |
      echo "Run \"pnpm dev\" to start dev server"

vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - GitHub.vscode-github-actions
    - sourcegraph.cody-ai
