on:
  workflow_dispatch:
  schedule:
    - cron: 5 0 * * *

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://www.tintaborneo.com/sitemap-index.xml
      - run: xmlstarlet sel -t -v '//sitemapindex/sitemap/loc' sitemap-index.xml > url.txt
      - uses: actions/upload-artifact@v3
        with:
          name: urls
          path: url.txt

  process:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: urls
      - uses: addnab/docker-run-action@v3
        with:
          image: wabarc/wayback
          options: -v ${{ github.workspace }}:/work
          run: cat /work/url.txt | wayback
