on:
  workflow_dispatch:
  schedule:
    - cron: 5 0 * * *

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - run: gem install wayback_archiver
      - run: wayback_archiver https://www.tintaborneo.com/sitemap-index.xml
