on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm run build
        env:
          ADMIN_ENDPOINT: ${{ secrets.ADMIN_ENDPOINT }}
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=tintaborneo-com
